version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app:cached 
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app:cached 
    command: tail -f /dev/null

  db:
    image: mysql:8.0
    volumes: 
      - ./data:/var/lib/mysql:cached 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
   
