version: '3'
services:
  master:
    build: .
    container_name: master
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    command: /app/backend/vendor/bin/yii serve 0.0.0.0:8080 -t /app/backend/web
    
