version: '3'

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  nginx:
    environment:
      - TZ=Asia/Almaty
    image: nginx:1.25-alpine3.18-perl
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/backend
      - ./frontend:/var/www/frontend
      - /var/www/backend/vendor
      - /var/www/frontend/node_modules
    networks:
      - backend
    ports:
      - 3000:80
      # - 443:443
    depends_on:
      # - frontend
      - backend

  backend:
    build:
      context: ./backend
    networks:
      - backend
    volumes:
      - ./backend:/var/www/backend
      - /var/www/backend/vendor
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/var/www/frontend
      - /var/www/frontend/node_modules
    networks:
      - frontend

  db:
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
    image: mysql:8.0
    networks:
      - backend
    ports:
      - 3306:3306 # TODO(annad): Remove this line!
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql:cached

  redis:
    image: redis:7.2.4-alpine3.19
    networks:
      - backend
    volumes:
      - ./docker/redis:/data:cached
    restart: always
